import type { Supplier, PurchaseOrder, ReceivingRecord } from './types';

export const mockSuppliers: Supplier[] = [
  {
    id: 'sup-001',
    name: 'Premium Fabrics Co.',
    code: 'PFC',
    status: 'active',
    contactName: 'Sarah Johnson',
    contactEmail: 'sarah@premiumfabrics.com',
    contactPhone: '(555) 123-4567',
    address: '123 Textile Ave, Los Angeles, CA 90001',
    paymentTerms: 'Net 30',
    leadTimeDays: 14,
    minimumOrderValue: 500,
    rating: 5,
    notes: 'Preferred supplier for jersey materials. Excellent quality.',
    createdAt: Date.now() - 90 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 7 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'sup-002',
    name: 'SportsTech Materials',
    code: 'STM',
    status: 'active',
    contactName: 'Mike Chen',
    contactEmail: 'mike@sportstechmaterials.com',
    contactPhone: '(555) 234-5678',
    address: '456 Industrial Blvd, Portland, OR 97201',
    paymentTerms: 'Net 45',
    leadTimeDays: 21,
    minimumOrderValue: 1000,
    rating: 4,
    notes: 'Good for moisture-wicking materials and technical fabrics.',
    createdAt: Date.now() - 60 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 14 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'sup-003',
    name: 'Global Thread Supply',
    code: 'GTS',
    status: 'active',
    contactName: 'Lisa Park',
    contactEmail: 'lisa@globalthread.com',
    contactPhone: '(555) 345-6789',
    address: '789 Commerce St, Dallas, TX 75201',
    paymentTerms: 'Net 30',
    leadTimeDays: 7,
    minimumOrderValue: 200,
    rating: 4,
    notes: 'Fast shipping. Good for thread and small components.',
    createdAt: Date.now() - 45 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 3 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'sup-004',
    name: 'EcoFabric Solutions',
    code: 'EFS',
    status: 'pending',
    contactName: 'James Wilson',
    contactEmail: 'james@ecofabric.com',
    contactPhone: '(555) 456-7890',
    address: '321 Green Way, Seattle, WA 98101',
    paymentTerms: 'Net 60',
    leadTimeDays: 28,
    minimumOrderValue: 750,
    rating: 3,
    notes: 'New supplier - sustainable materials. Evaluating quality.',
    createdAt: Date.now() - 7 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 7 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'sup-005',
    name: 'Budget Basics Inc.',
    code: 'BBI',
    status: 'inactive',
    contactName: 'Tom Rodriguez',
    contactEmail: 'tom@budgetbasics.com',
    contactPhone: '(555) 567-8901',
    address: '567 Value Lane, Phoenix, AZ 85001',
    paymentTerms: 'Net 15',
    leadTimeDays: 10,
    minimumOrderValue: 100,
    rating: 2,
    notes: 'Discontinued due to quality issues. Keep for reference.',
    createdAt: Date.now() - 180 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 30 * 24 * 60 * 60 * 1000,
  },
];

export const mockPurchaseOrders: PurchaseOrder[] = [
  {
    id: 'po-001',
    poNumber: 'PO-2024-001',
    supplierId: 'sup-001',
    supplierName: 'Premium Fabrics Co.',
    status: 'received',
    lineItems: [
      {
        id: 'li-001',
        materialId: 'mat-001',
        materialName: 'Jersey Polyester Blend',
        sku: 'JPB-001',
        quantityOrdered: 500,
        quantityReceived: 500,
        unitPrice: 12.50,
        unit: 'yards',
      },
      {
        id: 'li-002',
        materialId: 'mat-002',
        materialName: 'Elastic Waistband Material',
        sku: 'EWM-001',
        quantityOrdered: 200,
        quantityReceived: 200,
        unitPrice: 3.25,
        unit: 'yards',
      },
    ],
    subtotal: 6900,
    tax: 552,
    shipping: 150,
    total: 7602,
    expectedDeliveryDate: '2024-01-15',
    actualDeliveryDate: '2024-01-14',
    notes: 'First quarter fabric order',
    approvedBy: 'Admin',
    approvedAt: Date.now() - 45 * 24 * 60 * 60 * 1000,
    createdAt: Date.now() - 50 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 40 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'po-002',
    poNumber: 'PO-2024-002',
    supplierId: 'sup-002',
    supplierName: 'SportsTech Materials',
    status: 'partial',
    lineItems: [
      {
        id: 'li-003',
        materialId: 'mat-003',
        materialName: 'Moisture-Wicking Fabric',
        sku: 'MWF-001',
        quantityOrdered: 300,
        quantityReceived: 200,
        unitPrice: 18.00,
        unit: 'yards',
      },
      {
        id: 'li-004',
        materialId: 'mat-004',
        materialName: 'Mesh Ventilation Panels',
        sku: 'MVP-001',
        quantityOrdered: 150,
        quantityReceived: 0,
        unitPrice: 8.50,
        unit: 'sq ft',
      },
    ],
    subtotal: 6675,
    tax: 534,
    shipping: 200,
    total: 7409,
    expectedDeliveryDate: '2024-01-25',
    notes: 'Performance line materials',
    approvedBy: 'Admin',
    approvedAt: Date.now() - 20 * 24 * 60 * 60 * 1000,
    createdAt: Date.now() - 25 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 5 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'po-003',
    poNumber: 'PO-2024-003',
    supplierId: 'sup-003',
    supplierName: 'Global Thread Supply',
    status: 'approved',
    lineItems: [
      {
        id: 'li-005',
        materialId: 'mat-005',
        materialName: 'Industrial Sewing Thread',
        sku: 'IST-001',
        quantityOrdered: 50,
        quantityReceived: 0,
        unitPrice: 24.00,
        unit: 'spools',
      },
      {
        id: 'li-006',
        materialId: 'mat-006',
        materialName: 'Jersey Buttons',
        sku: 'JB-001',
        quantityOrdered: 1000,
        quantityReceived: 0,
        unitPrice: 0.15,
        unit: 'pieces',
      },
    ],
    subtotal: 1350,
    tax: 108,
    shipping: 25,
    total: 1483,
    expectedDeliveryDate: '2024-02-01',
    notes: 'Small components restock',
    approvedBy: 'Admin',
    approvedAt: Date.now() - 2 * 24 * 60 * 60 * 1000,
    createdAt: Date.now() - 5 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 2 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'po-004',
    poNumber: 'PO-2024-004',
    supplierId: 'sup-001',
    supplierName: 'Premium Fabrics Co.',
    status: 'draft',
    lineItems: [
      {
        id: 'li-007',
        materialId: 'mat-001',
        materialName: 'Jersey Polyester Blend',
        sku: 'JPB-001',
        quantityOrdered: 750,
        quantityReceived: 0,
        unitPrice: 12.50,
        unit: 'yards',
      },
    ],
    subtotal: 9375,
    tax: 750,
    shipping: 175,
    total: 10300,
    expectedDeliveryDate: '2024-02-15',
    notes: 'Q2 pre-order',
    createdAt: Date.now() - 1 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 1 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'po-005',
    poNumber: 'PO-2024-005',
    supplierId: 'sup-002',
    supplierName: 'SportsTech Materials',
    status: 'submitted',
    lineItems: [
      {
        id: 'li-008',
        materialId: 'mat-007',
        materialName: 'UV-Resistant Coating',
        sku: 'URC-001',
        quantityOrdered: 100,
        quantityReceived: 0,
        unitPrice: 45.00,
        unit: 'liters',
      },
    ],
    subtotal: 4500,
    tax: 360,
    shipping: 100,
    total: 4960,
    expectedDeliveryDate: '2024-02-10',
    notes: 'Outdoor product line materials',
    createdAt: Date.now() - 3 * 24 * 60 * 60 * 1000,
    updatedAt: Date.now() - 3 * 24 * 60 * 60 * 1000,
  },
];

export const mockReceivingRecords: ReceivingRecord[] = [
  {
    id: 'rec-001',
    purchaseOrderId: 'po-001',
    poNumber: 'PO-2024-001',
    supplierId: 'sup-001',
    supplierName: 'Premium Fabrics Co.',
    receivedAt: Date.now() - 40 * 24 * 60 * 60 * 1000,
    receivedBy: 'John Smith',
    lineItems: [
      {
        lineItemId: 'li-001',
        materialName: 'Jersey Polyester Blend',
        sku: 'JPB-001',
        quantityExpected: 500,
        quantityReceived: 500,
        quantityAccepted: 500,
        quantityRejected: 0,
        inspectionStatus: 'passed',
        notes: 'All units in excellent condition',
      },
      {
        lineItemId: 'li-002',
        materialName: 'Elastic Waistband Material',
        sku: 'EWM-001',
        quantityExpected: 200,
        quantityReceived: 200,
        quantityAccepted: 200,
        quantityRejected: 0,
        inspectionStatus: 'passed',
        notes: '',
      },
    ],
    inspectionStatus: 'passed',
    inspectionNotes: 'Full shipment received and inspected. All materials meet quality standards.',
    inventoryUpdated: true,
  },
  {
    id: 'rec-002',
    purchaseOrderId: 'po-002',
    poNumber: 'PO-2024-002',
    supplierId: 'sup-002',
    supplierName: 'SportsTech Materials',
    receivedAt: Date.now() - 5 * 24 * 60 * 60 * 1000,
    receivedBy: 'Jane Doe',
    lineItems: [
      {
        lineItemId: 'li-003',
        materialName: 'Moisture-Wicking Fabric',
        sku: 'MWF-001',
        quantityExpected: 300,
        quantityReceived: 200,
        quantityAccepted: 195,
        quantityRejected: 5,
        inspectionStatus: 'partial',
        notes: '5 yards had minor defects. Remaining 100 yards backordered.',
      },
    ],
    inspectionStatus: 'partial',
    inspectionNotes: 'Partial shipment. Waiting for backorder of 100 yards + mesh panels.',
    inventoryUpdated: true,
  },
];
